name: clean_architechture
description: A new Flutter application with clean architechture

publish_to: "none"

version: 1.0.0+2

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  #Network library
  retrofit: ^4.0.3
  pretty_dio_logger: ^1.3.1

  #State management, Dependencies injection library
  get_it: ^7.6.6
  flutter_bloc: ^8.1.3
  equatable: ^2.0.5
  injectable: ^2.3.2

  #Generate library
  json_serializable: ^6.7.1
  json_annotation: ^4.8.1
  freezed_annotation: ^2.4.1

  #Localization library
  sheet_loader_localization: ^0.2.0
  easy_localization: ^3.0.3
  easy_localization_loader: ^1.0.1+1

  #Firebase library
  firebase_analytics: ^10.8.0
  firebase_crashlytics: ^3.4.9
  firebase_core: ^2.24.2

  #Storage library
  shared_preferences: ^2.2.2
  path_provider: ^2.1.2

  #UI library
  cupertino_icons: ^1.0.6
  cached_network_image: ^3.3.1
  flutter_svg: ^2.0.9
  flutter_screenutil: ^5.9.0
  pull_to_refresh: ^2.0.0

dev_dependencies:
  build_runner: ^2.4.8
  flutter_gen_runner: ^5.4.0
  retrofit_generator: ^8.0.6
  flutter_test:
    sdk: flutter
  dart_code_metrics: ^5.7.3
  flutter_lints: ^3.0.1
  import_sorter: ^4.6.0
  change_app_package_name: ^1.1.0
  freezed: ^2.4.6
  injectable_generator: ^2.4.1

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - resources/langs/

flutter_gen:
  integrations:
    flutter_svg: true

import_sorter:
  comments: false
